config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: :show, param: :text
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  # параметры работы модуля шифрофания паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  attr_accessor :password

  has_many :questions, dependent: :destroy

  validates :email, :username, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :username, format: { with: /\A[a-zA-Z0-9_]+\z/}, length: { maximum: 40 }
  validates :header_color, format: { with: /\A#[a-f0-9]{6}\z/}, on: :update
  validates :password, presence: true, on: :create
  validates :password, confirmation: true

  before_validation { username&.downcase! }
  before_validation { email&.downcase! }
  before_save :encrypt_password

  # служебный метод, преобразующий бинарную строку в 16-ричный формат, для удобства хранения
  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email) # сперва находим кандидата по email

    # Сравнивается password_hash, а оригинальный парал так никогда и не сохраняется
    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS,  DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end

  private

  def encrypt_password
    if self.password.present?
      # создаем т. н. "соль" - рандомная строка усложняющая задачу хакерам
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      # создаем хэш пароля - длинная уникальная строка, из которой невозможно восстановить
      # исходный пароль
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS,  DIGEST.length, DIGEST)
      )
    end
  end
end

app/controllers/users_controller.rb
# Контроллер, управляющий пользователями. Должен уметь:
#
#   1. Показывать страницу пользователя
#   2. Создавать новых пользователей
#   3. Позволять пользователю редактировать свою страницу
#
class UsersController < ApplicationController

  before_action :load_user, except: %i[index create new]
  before_action :authorize_user, except: %i[index new create show]
  # Это действие отзывается, когда пользователь заходит по адресу /users
  def index
    @users = User.all
    @hashtags = Hashtag.with_questions
  end

  def new
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Пользователь успешно зарегестрирован!'
    else
      render 'new'
    end
  end

  def update
    @user = User.find params[:id]

    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      render 'edit'
    end
  end

  def destroy
    session[:user_id] = nil
    @user.destroy

    redirect_to root_path, notice: 'Профиль удален.'
  end

  def edit
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @new_question = @user.questions.build
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :username, :avatar_url, :header_color)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%# Страница редактирования пользователя %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>
      <div class="form-field">
        <%= f.label 'Цвет страницы профиля', class: 'form-label' %>
        <% if @user.header_color %>
          <%= f.color_field :header_color, value: @user.header_color %>
        <% else %>
          <%= f.color_field :header_color, value: "#005a55" %>
        <% end %>
      </div>
      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>
    <% end %>

    <div class="buffer-top-large buffer-bottom">
      Удалить профиль
    </div>

    <div class="user-actions">
      <%= button_to('Удалить', user_path(@user), method: "delete",
                    class: "button button-red button-small", data: { confirm: 'Точно удалить профиль?' }) %>
    </div>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда пользователь захочет посмотреть список пользователей %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <%# Этот код выводит каждого пользователя в цикле %>
  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%# Пользуемся аж тремя хелперами %>
          <%# link_to — генерирует ссылку %>
          <%# image_tag — генерирует картинку %>
          <%# user_avatar — достает из пользователя ссылку на картинку или подставляет дефолтную %>
          <%# Хелпер user_path(user) возвращает относительный путь %>
          <%# страницы пользователя, например /users/1 %>
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
        </div>
      </div>
  <% end %>

  <div class="flex-section-row">
    <div class="question-box">
      <% @hashtags.each do |hashtag| %>
        <span class="margin-both"><%= link_to "##{hashtag.text}", hashtag_path(hashtag.text), class: 'author-link' %></span>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%# Страница для регистрации нового пользователя. %>

<%# Обратите внимание, что она очень похожа на страницу редактирования юзера, %>
<%# что позволяет в подобных случаях использовать один и тот же паршиал form %>
<%# в обоих страницах. %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for @user do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

app/views/users/show.html.erb
<%# В шаблоне show мы пишем html-код для вывода внутреннго содержимого %>
<%# страницы пользователя, которая будет показана по адресу /users/1 %>

<%# Блок с информацией о пользователей %>

  <div class="user-header text-center"
    <% if @user.header_color %>
      <%= "style=background-color:#{@user.header_color}"%>
    <% end %> >
  <h1 class="title-medium">
    <%# Выводим имя пользователя %>
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%# Рисуем аватарку пользователя. Мы используем хелперы image_tag, %>
    <%# встроенный в rails, и наш user_avatar %>
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    <%# Выводим никнейм пользователя с символом «@» перед ним. %>
    @<%= @user.username %>
  </h2>

  <div class="user-ask-button container text-center">
    <%# Используем встроенный в rails хелпер link_to %>
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>
</div>

<%# Блок с формой для задавания пользователю вопроса %>
<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%# Мы используем хелпер form_for, принимающий на вход блок erb-кода, %>
      <%# в котором доступна переменная f, содержащая так называемый form %>
      <%# builder, с помощью которого можно делать поля формы для нового %>
      <%# вопроса. %>
      <%= form_for @new_question do |f| %>
        <%# С помощью объекта для создания полей формы, связанной с моделью %>
        <%# @new_question Мы создаем инпуты с нужными полями для формы, %>
        <%# значения будут подставлены rails автоматически. %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <%= recaptcha_tags size: 'compact' unless current_user.present? %>

        <div class="form-action">
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="column-3-4">
  <div class="question questions-total buffer-top text-lead ">
    Всего <%= @questions.size %> <%= inclination(@questions.size, 'вопрос', 'вопроса', 'вопросов') %>,
    <%= no_answer = no_answer(@questions) %> без ответа, <%= @questions.size - no_answer %> с ответом.
  </div>
</div>

<%# Блок со списком вопросов к пользователю %>
<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <%# Обратите внимание, как мы делаем цикл по всем вопросам, точно %>
      <%# также, как мы делали циклы в ruby %>
      <% @questions.each do |question| %>
        <%# Мы рисуем здесь для кажого вопроса в списке вопросов фрагмент %>
        <%# (паршал), передавая в него текущий вопрос. Это очень похоже на %>
        <%# вызов метода в ruby %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>