config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: :show, param: :text
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Хорошие вопросы</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>

    <%# Выводим в хэдере информацию для логина/авторизации/регистрации %>
    <div class="header-nav">
      <%# Если есть текущий юзер (значит он залогинен) %>
      <% if current_user %>
        <%# Даем ссылки на его профиль и на логаут %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to 'Выйти', session_path, data: {method: :delete} %>
      <% else %>
        <%# Если нету — ссылки на регистрацию и логин %>
        <%= link_to 'Зарегистрироваться', new_user_path,
                    class: 'button button-light button-small' %>
        <%= link_to 'Войти', new_session_path,
                    class: 'button button-light button-small' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <%# Выводим сообщение об ошибке или уведомление для пользователя. %>
    <%# Если в объеккте flash есть что-то, выводим содержимое на страницу, %>
    <%# если нет, игнорируем этот блок. %>
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</div>
</body>
</html>